/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StateLabRouteImport } from './routes/state-lab'
import { Route as ResultLabRouteImport } from './routes/result-lab'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GCodeRouteImport } from './routes/g.$code'

const StateLabRoute = StateLabRouteImport.update({
  id: '/state-lab',
  path: '/state-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultLabRoute = ResultLabRouteImport.update({
  id: '/result-lab',
  path: '/result-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/result-lab': typeof ResultLabRoute
  '/state-lab': typeof StateLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/result-lab': typeof ResultLabRoute
  '/state-lab': typeof StateLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/result-lab': typeof ResultLabRoute
  '/state-lab': typeof StateLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/dev' | '/result-lab' | '/state-lab' | '/g/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/dev' | '/result-lab' | '/state-lab' | '/g/$code'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/dev'
    | '/result-lab'
    | '/state-lab'
    | '/g/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DevRoute: typeof DevRoute
  ResultLabRoute: typeof ResultLabRoute
  StateLabRoute: typeof StateLabRoute
  GCodeRoute: typeof GCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state-lab': {
      id: '/state-lab'
      path: '/state-lab'
      fullPath: '/state-lab'
      preLoaderRoute: typeof StateLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result-lab': {
      id: '/result-lab'
      path: '/result-lab'
      fullPath: '/result-lab'
      preLoaderRoute: typeof ResultLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DevRoute: DevRoute,
  ResultLabRoute: ResultLabRoute,
  StateLabRoute: StateLabRoute,
  GCodeRoute: GCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
