/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FxLabRouteImport } from './routes/fx-lab'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AnnonceLabRouteImport } from './routes/annonce-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GCodeRouteImport } from './routes/g.$code'

const FxLabRoute = FxLabRouteImport.update({
  id: '/fx-lab',
  path: '/fx-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonceLabRoute = AnnonceLabRouteImport.update({
  id: '/annonce-lab',
  path: '/annonce-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonce-lab': typeof AnnonceLabRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/fx-lab': typeof FxLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonce-lab': typeof AnnonceLabRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/fx-lab': typeof FxLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annonce-lab': typeof AnnonceLabRoute
  '/demo': typeof DemoRoute
  '/dev': typeof DevRoute
  '/fx-lab': typeof FxLabRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/annonce-lab' | '/demo' | '/dev' | '/fx-lab' | '/g/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/annonce-lab' | '/demo' | '/dev' | '/fx-lab' | '/g/$code'
  id:
    | '__root__'
    | '/'
    | '/annonce-lab'
    | '/demo'
    | '/dev'
    | '/fx-lab'
    | '/g/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnonceLabRoute: typeof AnnonceLabRoute
  DemoRoute: typeof DemoRoute
  DevRoute: typeof DevRoute
  FxLabRoute: typeof FxLabRoute
  GCodeRoute: typeof GCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fx-lab': {
      id: '/fx-lab'
      path: '/fx-lab'
      fullPath: '/fx-lab'
      preLoaderRoute: typeof FxLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonce-lab': {
      id: '/annonce-lab'
      path: '/annonce-lab'
      fullPath: '/annonce-lab'
      preLoaderRoute: typeof AnnonceLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnonceLabRoute: AnnonceLabRoute,
  DemoRoute: DemoRoute,
  DevRoute: DevRoute,
  FxLabRoute: FxLabRoute,
  GCodeRoute: GCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
