INSERT INTO public.roles (
  slug, name_fr, icon, faction, type, secondary_type, presence, phase_activation,
  difficulte, min_players, emergent, police_verdict, capacite_full_text, carte_app,
  description, target_mode, instruction_verb, usage_label, set_id, draw_weight,
  is_special, frequency_label
) VALUES (
  'avocat',
  'L''Avocat',
  '⚖️',
  'Civil',
  'SUPPORT',
  NULL,
  'OPTIONAL',
  'CONTINU',
  'Facile',
  6,
  false,
  'innocent',
  'Tu vois la faction des personnes emprisonnées.',
  'passive_auto',
  'Avocat du barreau, tu connais les dossiers : tu vois la faction de chaque joueur actuellement en prison.',
  'none',
  'Observe',
  'Permanent',
  'set1',
  1.0,
  false,
  'passif'
)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  icon = EXCLUDED.icon,
  faction = EXCLUDED.faction,
  type = EXCLUDED.type,
  presence = EXCLUDED.presence,
  phase_activation = EXCLUDED.phase_activation,
  difficulte = EXCLUDED.difficulte,
  police_verdict = EXCLUDED.police_verdict,
  capacite_full_text = EXCLUDED.capacite_full_text,
  carte_app = EXCLUDED.carte_app,
  description = EXCLUDED.description,
  target_mode = EXCLUDED.target_mode,
  instruction_verb = EXCLUDED.instruction_verb,
  usage_label = EXCLUDED.usage_label,
  frequency_label = EXCLUDED.frequency_label;