-- Lore : courte phrase d'ambiance pour chaque rôle (colonne description).
-- Rendue en italique « … » sur la fiche de rôle (menu d'aide) et la révélation.

UPDATE public.roles SET description = 'Une présence veille en secret sur un inconnu — et s''interposera, une seule fois, devant la mort.' WHERE slug = 'ange_gardien';
UPDATE public.roles SET description = 'Trois fioles dans sa sacoche : la vie, la mort et la vérité, à garder ou à offrir.' WHERE slug = 'apothicaire';
UPDATE public.roles SET description = 'Dans l''ombre du Détective, il recoupe les indices et resserre le cercle des suspects.' WHERE slug = 'assistant_du_detective';
UPDATE public.roles SET description = 'Maître du barreau, il connaît le dossier de chaque détenu mieux que quiconque.' WHERE slug = 'avocat';
UPDATE public.roles SET description = 'Le bourreau du manoir : quand une cellule a gardé son hôte assez longtemps, il abaisse la hache.' WHERE slug = 'executeur';
UPDATE public.roles SET description = 'Elle borde un convive pour la nuit — à l''abri du danger, mais privé de ses moyens.' WHERE slug = 'babysitter';
UPDATE public.roles SET description = 'Son instinct ne pointe pas le nord : il dit si deux cœurs battent pour le même camp.' WHERE slug = 'boussole';
UPDATE public.roles SET description = 'Une tournée offerte, et l''un des deux convives finit ivre… l''autre, simplement protégé.' WHERE slug = 'barman';
UPDATE public.roles SET description = 'Derrière ses fourneaux dort un couteau bien aiguisé, prêt à servir un dernier plat.' WHERE slug = 'cuisinier';
UPDATE public.roles SET description = 'L''enquêteur du manoir : il sonde les rôles et orchestre la table, mais ne prend jamais part au vote.' WHERE slug = 'detective';
UPDATE public.roles SET description = 'Il glisse une lettre anonyme dans une poche — à charge pour le destinataire d''en deviner l''auteur.' WHERE slug = 'facteur';
UPDATE public.roles SET description = 'Toujours sur ses gardes, il sait au matin qui, dans la nuit, a posé les yeux sur lui.' WHERE slug = 'guetteur';
UPDATE public.roles SET description = 'Curieux jusqu''à l''indiscrétion, il feuillette en secret le carnet de soupçons d''un autre.' WHERE slug = 'journaliste';
UPDATE public.roles SET description = 'Garant d''une justice patiente, il peut rouvrir une cellule et rendre sa liberté à un détenu.' WHERE slug = 'juge';
UPDATE public.roles SET description = 'Loyal jusqu''au sacrifice, il s''interpose pour son protégé — quitte à tomber, entraînant l''assassin.' WHERE slug = 'majordome';
UPDATE public.roles SET description = 'Penché sur chaque dépouille, il arrache aux morts le nom de ce qu''ils furent.' WHERE slug = 'medecin_legiste';
UPDATE public.roles SET description = 'Il entend le murmure des défunts au Conseil des morts, sans jamais pouvoir leur répondre.' WHERE slug = 'medium';
UPDATE public.roles SET description = 'Un inconnu lui est lié, et le doute le ronge : faut-il le protéger… ou l''abattre avant qu''il ne frappe ?' WHERE slug = 'paranoiaque';
UPDATE public.roles SET description = 'Vieux limier du manoir, il flaire d''un regard si un convive sent le soufre.' WHERE slug = 'policier';
UPDATE public.roles SET description = 'Sa bénédiction rend un être intouchable — mais que la foule l''emprisonne, et les Civils sont perdus.' WHERE slug = 'saint';
UPDATE public.roles SET description = 'Il a entrevu, dès le départ, le vrai visage d''un Civil : un allié sûr dans la tempête.' WHERE slug = 'temoin';
UPDATE public.roles SET description = 'Il chérit un être en silence ; qu''on y touche, et la lame de la vengeance s''éveille.' WHERE slug = 'vengeur';
UPDATE public.roles SET description = 'Rideau entrouvert, il surveille un seul logis et démasque quiconque ose s''en approcher.' WHERE slug = 'voisin';
UPDATE public.roles SET description = 'Une parole venimeuse lui suffit : il pointe du doigt et fait peser le soupçon sur un innocent.' WHERE slug = 'accusateur';
UPDATE public.roles SET description = 'Il ne se salit jamais les mains — il glisse un couteau anonyme à qui fera le sale travail.' WHERE slug = 'armurier';
UPDATE public.roles SET description = 'Caméléon du manoir, il endosse l''identité d''un absent pour égarer toutes les enquêtes.' WHERE slug = 'usurpateur';
UPDATE public.roles SET description = 'Sous le voile de ses cartes, il lit les soupçons d''un convive et les rapporte aux siens.' WHERE slug = 'cartomancien';
UPDATE public.roles SET description = 'Quand l''assassin frappe, il efface tout : ni corps reconnaissable, ni indice, ni nom.' WHERE slug = 'cleaner';
UPDATE public.roles SET description = 'Il désigne deux proies et laisse le hasard décider laquelle ne verra pas l''aube.' WHERE slug = 'croque_mitaine';
UPDATE public.roles SET description = 'Il maquille une cible à jamais : les enquêteurs n''en tireront plus que du brouillard.' WHERE slug = 'falsificateur';
UPDATE public.roles SET description = 'Un secret bien placé, et sa victime se retrouve muselée le temps d''un tour.' WHERE slug = 'maitre_chanteur';
UPDATE public.roles SET description = 'Il tire les fils d''un convive et lui fait jouer, une fois, une partition qui n''est pas la sienne.' WHERE slug = 'marionnettiste';
UPDATE public.roles SET description = 'Dès la première nuit, il perce à jour le rôle exact d''un convive et le souffle à son camp.' WHERE slug = 'mouchard';
UPDATE public.roles SET description = 'Rien n''est laissé au hasard : il marque sa proie à l''avance, qui s''éteindra au tour suivant.' WHERE slug = 'stratege';
UPDATE public.roles SET description = 'Le maître du crime : dans l''ombre il choisit ses victimes, et un Acolyte reprendra sa lame s''il tombe.' WHERE slug = 'tueur';
UPDATE public.roles SET description = 'Doigts agiles, il subtilise l''objet le plus précieux d''un vivant… ou d''un mort.' WHERE slug = 'voleur';
UPDATE public.roles SET description = 'Patient et méthodique, il rêve d''un manoir où chaque survivant porte son poison dans les veines.' WHERE slug = 'empoisonneur';
UPDATE public.roles SET description = 'Il noue deux destins en secret : ils vivront et tomberont ensemble — et lui avec eux.' WHERE slug = 'entremetteur';
UPDATE public.roles SET description = 'Déshérité et rancunier, il enquête sous des airs honnêtes pour mieux servir la victoire des Méchants.' WHERE slug = 'heritier_dechu';
UPDATE public.roles SET description = 'Sans visage propre, il revêt le rôle du dernier tombé pour continuer la mascarade.' WHERE slug = 'imitateur';
UPDATE public.roles SET description = 'Il proclame qui l''emportera, et prie de vivre assez longtemps pour voir sa prophétie s''accomplir.' WHERE slug = 'oracle';
UPDATE public.roles SET description = 'Elle tisse ses pièges autour de deux proies ; qu''on vote contre elle, et la toile se referme.' WHERE slug = 'veuve_noire';
UPDATE public.roles SET description = 'Réveillé par la première morsure, il traque les buveurs de sang et plante son pieu sans trembler.' WHERE slug = 'chasseur_de_vampire';
UPDATE public.roles SET description = 'Gardien des reliques maudites, il les distribue jusqu''à ce que le Cœur du Manoir trouve une main.' WHERE slug = 'conservateur';
UPDATE public.roles SET description = 'Joueur invétéré, il mise des vies aux dés et compte bien rester le dernier debout.' WHERE slug = 'parieur_tricheur';
UPDATE public.roles SET description = 'À chaque nuit, une nouvelle morsure : son clan grandit dans l''ombre jusqu''à dominer le manoir.' WHERE slug = 'vampire';
